// Generated by CoffeeScript 1.7.1
var top;

top = __dirname + '/../';

module.exports = {
  controllers: top + 'app/controllers',
  models: top + 'app/models',
  views: top + 'app/views',
  "public": top + 'public',
  lib: top + 'lib',
  stylesheets: top + 'assets/stylesheets',
  javascripts: top + 'assets/javascripts',
  templates: top + 'assets/templates'
};
